# Generated by Django 2.2.1 on 2019-05-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='page_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
