# Generated by Django 2.2.1 on 2019-05-29 14:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190529_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
