# Generated by Django 2.2.1 on 2019-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglistingpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='date_composed',
            field=models.DateField(auto_now=True, verbose_name='Composition Date'),
        ),
    ]
