# Generated by Django 2.2.1 on 2019-05-29 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetailpage_date_composed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='date_composed',
            field=models.DateField(default=datetime.date.today, verbose_name='Composition Date'),
        ),
    ]
