# Generated by Django 2.2.1 on 2019-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190529_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(default='teaser', help_text='Teaser used on the blog listing page', max_length=100),
            preserve_default=False,
        ),
    ]
