# Generated by Django 2.2.1 on 2019-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogdetailpage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(blank=True, help_text='Teaser used on the blog listing page', max_length=100, null=True),
        ),
    ]
