# Generated by Django 2.2.1 on 2019-05-29 15:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190529_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Teaser text will show on the blog listing page', null=True),
        ),
    ]
