# Generated by Django 2.2.1 on 2019-05-23 13:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190519_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_story',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
