# Generated by Django 2.2.1 on 2019-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
