# Generated by Django 2.2.1 on 2019-05-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecarouselimages_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
