# Generated by Django 2.2.1 on 2019-05-28 12:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_feature_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_story',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
